<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.megafair.jinfra.vibraapi</groupId>
        <artifactId>vibra-s2s-api</artifactId>
        <version>0.20.0-3-15-1-2025-05-27</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>vibra-s2s-api-shared</artifactId>

    <properties>
    </properties>
    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-jackson</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-reactive-jaxb</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-validator</artifactId>
        </dependency>

        <!-- remove if not using servlets -->
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-undertow</artifactId>
        </dependency>
        <!-- remove if not using vertx web -->
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-reactive-routes</artifactId>
        </dependency>

<!--        <dependency>-->
<!--            <groupId>io.quarkus</groupId>-->
<!--            <artifactId>quarkus-amazon-lambda-rest</artifactId>-->
<!--        </dependency>-->

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>io.vavr</groupId>
            <artifactId>vavr</artifactId>
            <version>${io.vavr.version}</version>
        </dependency>

        <dependency>
            <groupId>io.megafair.jinfra.foundation</groupId>
            <artifactId>mf-fnd-contract-vibra-client-auth</artifactId>
        </dependency>
        <dependency>
            <groupId>io.megafair.jinfra.foundation</groupId>
            <artifactId>mf-fnd-web-session-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>io.megafair.jinfra.foundation</groupId>
            <artifactId>mf-fnd-auth-shared</artifactId>
        </dependency>
        <dependency>
            <groupId>io.megafair.jinfra.foundation</groupId>
            <artifactId>mf-fnd-geoip</artifactId>
        </dependency>
        <dependency>
            <groupId>io.megafair.jinfra.foundation</groupId>
            <artifactId>mf-fnd-player</artifactId>
        </dependency>
        <dependency>
            <groupId>io.megafair.jinfra.foundation</groupId>
            <artifactId>mf-fnd-game</artifactId>
        </dependency>
        <dependency>
            <groupId>io.megafair.jinfra.foundation</groupId>
            <artifactId>mf-fnd-scheduler</artifactId>
        </dependency>
        <dependency>
            <groupId>io.megafair.jinfra.foundation</groupId>
            <artifactId>mf-fnd-jwt-build</artifactId>
        </dependency>
        <dependency>
            <groupId>io.megafair.jinfra.foundation</groupId>
            <artifactId>mf-fnd-user-registration-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.megafair.external.maxmind.db</groupId>
            <artifactId>geolite2-city</artifactId>
            <version>${maxmind.db.geolite2-city.version}</version>
            <type>tar.gz</type>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-config-yaml</artifactId>
        </dependency>

        <dependency>
            <groupId>io.megafair.jinfra.foundation</groupId>
            <artifactId>mf-fnd-web-base</artifactId>
        </dependency>
        <dependency>
            <groupId>io.megafair.jinfra.foundation</groupId>
            <artifactId>mf-fnd-contract-mf-common</artifactId>
        </dependency>
        <dependency>
            <groupId>io.megafair.jinfra.foundation</groupId>
            <artifactId>mf-fnd-cache-introspection</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5-mockito</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-engine -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.testcontainers/postgresql -->
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>postgresql</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5-mockito</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5-mockito</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>