<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.megafair.jinfra.vibraapi</groupId>
    <artifactId>vibra-s2s-api</artifactId>


    <version>0.20.0-3-15-1-2025-05-27</version>

    <packaging>pom</packaging>
    <modules>
        <module>vibra-s2s-api-shared</module>
        <module>vibra-s2s-api-lambda-rest-app</module>
        <module>vibra-s2s-api-rest-app</module>
    </modules>
    <properties>
        <!-- quarkus -->
        <maven.compiler.release>17</maven.compiler.release>
        <!--        <maven.compiler.target>11</maven.compiler.target>-->
        <!--        <maven.compiler.source>11</maven.compiler.source>-->
        <assembly-plugin.version>3.7.1</assembly-plugin.version>
        <compiler-plugin.version>3.13.0</compiler-plugin.version>
        <maven.compiler.parameters>true</maven.compiler.parameters>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <quarkus-plugin.version>3.2.5.Final</quarkus-plugin.version>
        <quarkus.platform.version>3.15.1</quarkus.platform.version>
        <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
        <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
        <surefire-plugin.version>3.3.1</surefire-plugin.version>
        <!-- quarkus end -->

        <allogy-maven-plugin.version>1.2.0</allogy-maven-plugin.version>
        <io.vavr.version>1.0.0-alpha-4</io.vavr.version>

        <maxmind.db.geolite2-city.version>20240924</maxmind.db.geolite2-city.version>

        <jandex-maven-plugin-version>3.2.2</jandex-maven-plugin-version>


        <mf.foundation.version>2330-1.202.0-3-15-1-2025-06-16-SNAPSHOT</mf.foundation.version>

    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>${quarkus.platform.artifact-id}</artifactId>
                <version>${quarkus.platform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.megafair.jinfra.foundation</groupId>
                <artifactId>mf-fnd-cache-introspection</artifactId>
                <version>${mf.foundation.version}</version>
            </dependency>
            <dependency>
                <groupId>io.megafair.jinfra.foundation</groupId>
                <artifactId>mf-fnd-contract-vibra-client-auth</artifactId>
                <version>${mf.foundation.version}</version>
            </dependency>
            <dependency>
                <groupId>io.megafair.jinfra.foundation</groupId>
                <artifactId>mf-fnd-contract-mf-common</artifactId>
                <version>${mf.foundation.version}</version>
            </dependency>
            <dependency>
                <groupId>io.megafair.jinfra.foundation</groupId>
                <artifactId>mf-fnd-auth-shared</artifactId>
                <version>${mf.foundation.version}</version>
            </dependency>
            <dependency>
                <groupId>io.megafair.jinfra.foundation</groupId>
                <artifactId>mf-fnd-web-session-redis</artifactId>
                <version>${mf.foundation.version}</version>
            </dependency>
            <dependency>
                <groupId>io.megafair.jinfra.foundation</groupId>
                <artifactId>mf-fnd-geoip</artifactId>
                <version>${mf.foundation.version}</version>
            </dependency>
            <dependency>
                <groupId>io.megafair.jinfra.foundation</groupId>
                <artifactId>mf-fnd-player</artifactId>
                <version>${mf.foundation.version}</version>
            </dependency>
            <dependency>
                <groupId>io.megafair.jinfra.foundation</groupId>
                <artifactId>mf-fnd-game</artifactId>
                <version>${mf.foundation.version}</version>
            </dependency>
            <dependency>
                <groupId>io.megafair.jinfra.foundation</groupId>
                <artifactId>mf-fnd-micrometer</artifactId>
                <version>${mf.foundation.version}</version>
            </dependency>
            <dependency>
                <groupId>io.megafair.jinfra.foundation</groupId>
                <artifactId>mf-fnd-scheduler</artifactId>
                <version>${mf.foundation.version}</version>
            </dependency>
            <dependency>
                <groupId>io.megafair.jinfra.foundation</groupId>
                <artifactId>mf-fnd-jwt-build</artifactId>
                <version>${mf.foundation.version}</version>
            </dependency>
            <dependency>
                <groupId>io.megafair.jinfra.foundation</groupId>
                <artifactId>mf-fnd-user-registration-client</artifactId>
                <version>${mf.foundation.version}</version>
            </dependency>
            <dependency>
                <groupId>io.megafair.jinfra.foundation</groupId>
                <artifactId>mf-fnd-web-base</artifactId>
                <version>${mf.foundation.version}</version>
            </dependency>
            <dependency>
                <groupId>io.megafair.jinfra.foundation</groupId>
                <artifactId>mf-fnd-test-common</artifactId>
                <version>${mf.foundation.version}</version>
            </dependency>
            <dependency>
                <groupId>io.megafair.jinfra.foundation</groupId>
                <artifactId>mf-fnd-light-game-cache-data-provider</artifactId>
                <version>${mf.foundation.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>

    </dependencies>
    <build>
        <extensions>
            <!-- https://github.com/Allogy/maven-s3-wagon -->

            <extension>
                <groupId>com.allogy.maven.wagon</groupId>
                <artifactId>maven-s3-wagon</artifactId>
                <version>${allogy-maven-plugin.version}</version>
            </extension>
        </extensions>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <version>3.4.0</version>
                    <executions>
                        <execution>
                            <id>unpack-maxmind</id>
                            <goals>
                                <goal>unpack</goal>
                            </goals>
                            <phase>generate-resources</phase>
                            <configuration>
                                <artifactItems>
                                    <artifactItem>
                                        <groupId>io.megafair.external.maxmind.db</groupId>
                                        <artifactId>geolite2-city</artifactId>
                                        <version>${maxmind.db.geolite2-city.version}</version>
                                        <type>tar.gz</type>
                                        <outputDirectory>${project.build.sourceDirectory}/../resources</outputDirectory>
                                        <!--                                    <outputDirectory>${project.build.outputDirectory}/</outputDirectory>-->
                                        <includes>**/*.mmdb</includes>
                                        <fileMappers>
                                            <org.codehaus.plexus.components.io.filemappers.RegExpFileMapper>
                                                <pattern>^\QGeoLite2-City_${maxmind.db.geolite2-city.version}/\E
                                                </pattern>
                                                <replacement>./</replacement>
                                            </org.codehaus.plexus.components.io.filemappers.RegExpFileMapper>
                                        </fileMappers>
                                    </artifactItem>
                                </artifactItems>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
            </resource>
            <resource>
                <directory>src/main/resources-filtered</directory>
                <filtering>true</filtering>
                <includes>
                    <include>**/mf-version.properties</include>
                </includes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.platform.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                            <goal>generate-code</goal>
                            <goal>generate-code-tests</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>io.smallrye</groupId>
                <artifactId>jandex-maven-plugin</artifactId>
                <version>${jandex-maven-plugin-version}</version>
                <executions>
                    <execution>
                        <id>make-index</id>
                        <goals>
                            <goal>jandex</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${compiler-plugin.version}</version>
            </plugin>

            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${surefire-plugin.version}</version>
                <configuration>
                    <systemPropertyVariables>
                        <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                        <maven.home>${maven.home}</maven.home>
                        <user.timezone>UTC</user.timezone>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <id>append-to-properties</id>
                        <phase>process-test-resources</phase>
                        <configuration>
                            <target>
                                <echo file="${project.build.testOutputDirectory}/application.properties" append="true">
                                    <!--                                    ${line.separator}#Disabling dev services for datasource ${line.separator}quarkus.datasource.devservices.enabled=false-->
                                    ${line.separator}#Disabling dev services for datasource ${line.separator}quarkus.datasource.devservices.image-name=mf-postgres-test-temp:${mf.foundation.version}
                                    ${line.separator}#Disabling dev services for datasource ${line.separator}quarkus.datasource.devservices.db-name=quarkus_test
                                    ${line.separator}#Disabling dev services for datasource ${line.separator}quarkus.datasource.devservices.username=master
                                    ${line.separator}#Disabling dev services for datasource ${line.separator}quarkus.datasource.devservices.password=postgres-local
                                    ${line.separator}quarkus.http.test-port=0
                                    ${line.separator}quarkus.redis.devservices.shared=true
                                    ${line.separator}quarkus.redis.devservices.image-name=mf-redis-test-temp:${mf.foundation.version}
                                    ${line.separator}mf.conf.supported-protocol=vibra
<!--                                    ${line.separator}mf.conf.cached-service.around-invoker.enabled=false-->
                                </echo>
                            </target>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>native</id>
            <activation>
                <property>
                    <name>native</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <version>${surefire-plugin.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                                <configuration>
                                    <systemPropertyVariables>
                                        <native.image.path>
                                            ${project.build.directory}/${project.build.finalName}-runner
                                        </native.image.path>
                                        <java.util.logging.manager>org.jboss.logmanager.LogManager
                                        </java.util.logging.manager>
                                        <maven.home>${maven.home}</maven.home>
                                    </systemPropertyVariables>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
            <properties>
                <quarkus.package.type>native</quarkus.package.type>
            </properties>
        </profile>
    </profiles>
    <repositories>
        <repository>
            <id>mf-repo-snapshot</id>
            <url>${mf-repo-snapshot-url}</url>
        </repository>
        <repository>
            <id>mf-repo-release</id>
            <url>${mf-repo-release-url}</url>
        </repository>
    </repositories>
    <distributionManagement>
        <repository>
            <id>mf-repo-release</id>
            <name>MF Release Repository</name>
            <url>${mf-repo-release-url}</url>
        </repository>
        <snapshotRepository>
            <id>mf-repo-snapshot</id>
            <name>MF Snapshot Repository</name>
            <url>${mf-repo-snapshot-url}</url>
        </snapshotRepository>
    </distributionManagement>
</project>
