quarkus.http.port=9093
quarkus.management.enabled=true
quarkus.management.port=9094

mf.is_local=true
mf.game-url.layout=LEGACY
mf.geo.redirect.uri = /static/forbidden.html
mf.platforms.megafair.baseURL=https://prod.bsg-mock.mfgapi.com
mf.platforms.megafair.redirectURL=https://prod.bsg-mock.mfgapi.com/homeUrl

#mf.domain.root=aaa.com

quarkus.log.category."io.megafair.jinfra.foundation.scheduler.DynamicSchedulerRegister".level=DEBUG

#quarkus.rest-client.vibra-authenticate-api.verify-host=false
quarkus.micrometer.export.datadog.enabled=false


%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=master
%dev.quarkus.datasource.password=postgres-local
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus_main_3_1_0

quarkus.log.file.path=target/quarkus.log
quarkus.log.file.enable=true
quarkus.log.file.json=false

mf.registration.transaction.mode=http
mf.registration.transaction.api=http://localhost:5568
mf.conf.contract.s2s.front-api.url=https://game-init-api.local.mfgapi.com/initData