mf.session.redis.protocol=redis://
mf.session.redis.hosts:localhost:6379
mf.session.redis.password=redis1redis1

quarkus.application.name=vibra-s2s-api-gameprovider
quarkus.native.add-all-charsets=true
quarkus.native.resources.includes=GeoLite2*,jwt_keys/**
quarkus.ssl.native=true
quarkus.devservices.enabled=false

quarkus.http.access-log.enabled=true
quarkus.http.access-log.pattern=%h %l %u %t "%r" %s %b %D ms %{ALL_REQUEST_HEADERS}
quarkus.http.access-log.exclude-pattern=/q/metrics
quarkus.http.record-request-start-time=true

quarkus.rest-client.authenticate-api.connect-timeout=1000

#quarkus.rest-client.authenticate-api-aln.uri=https://bo.roocasino.net/apis/megafair
#
#quarkus.rest-client.authenticate-api-mfmock.uri=https://prod.bsg-mock.mfgapi.com

#quarkus.rest-client.betresult-api.uri=${MF_BSG_BRAND_MOCK_BETRESULT_API_URI:http://localhost:8080}
#https://3l0cdoerei.execute-api.us-west-2.amazonaws.com/
#quarkus.rest-client.authenticate-api.user-agent=MegaFairClient/1.0

quarkus.rest-client.headers."X-MF-APP-NAME"=${quarkus.application.name}
quarkus.rest-client.headers."X-MF-APP-ID"=${quarkus.uuid}
quarkus.rest-client.read-timeout=1000
quarkus.rest-client.user-agent=MegaFairClient/1.0

#quarkus.http.header.Pragma.value=no-cache
#quarkus.http.header.Pragma.path=/headers/pragma
#quarkus.http.header.Pragma.methods=GET,HEAD
quarkus.rest-client.logging.scope=all
#request-response
quarkus.rest-client.logging.body-limit=10000
quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG

#quarkus.redis.redis-session.hosts=redis://localhost:6379/
#quarkus.redis.redis-session.password=redis1redis1
quarkus.redis.redis-session.timeout=5s
quarkus.redis.redis-session.hosts-provider-name=redis-session-hosts-provider
quarkus.redis.redis-blocking.hosts-provider-name=redis-session-hosts-provider
#keep-alive
quarkus.redis.redis-session.tcp.keep-alive=true
quarkus.redis.redis-session.tcp.so-linger=4000s
quarkus.redis.redis-session.tcp.idle-timeout=6000s
#quarkus.redis.redis-session.tcp.
quarkus.redis.redis-session.max-pool-size=10
#quarkus.redis.tcp.idle-timeout=
#quarkus.redis.tcp.so-linger=300s
quarkus.redis.max-pool-size=6
quarkus.redis.tcp.keep-alive=true
quarkus.redis.tcp.idle-timeout=600s
quarkus.redis.tls.enabled=false
quarkus.redis.tls.trust-all=false

# shutdown handling
quarkus.shutdown.delay-enabled=true
quarkus.shutdown.delay=20s

#postgres
quarkus.hibernate-orm.database.generation=validate

quarkus.datasource.metrics.enabled=true
quarkus.datasource.jdbc.enable-metrics=true
quarkus.datasource.jdbc.telemetry=true
mf.player.progress.max-value-size-in-bytes=50000
##-

quarkus.log.min-level=TRACE
quarkus.log.category."io.vertx.redis".level=TRACE
quarkus.log.category."io.quarkus.redis".level=TRACE
quarkus.log.category."io.megafair".level=INFO
quarkus.log.console.format=%d{HH:mm:ss} %-5p instanceId=${quarkus.uuid}, traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled}, platformId=%X{platformId}, extUserId=%X{extUserId}, prevSessionId=%X{prevSessionId}, sessionId=%X{sessionId}, extGameSessionId=%X{extGameSessionId} [%c{2.}] (%t) %s%e%n
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %h %N[%i] %-5p instanceId=${quarkus.uuid}, traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled}, platformId=%X{platformId}, extUserId=%X{extUserId}, prevSessionId=%X{prevSessionId}, sessionId=%X{sessionId}, extGameSessionId=%X{extGameSessionId} [%c{3.}] (%t) %s%e%n

mf.service.name=${quarkus.application.name}
mf.environment.name=local-${USER:-unknown}
mf.resource.attributes=instId=${quarkus.uuid},service.name=${mf.service.name},deployment.environment=${mf.environment.name}
mf.otel.collector.host=localhost
mf.otel.collector.traces.port=4317
mf.otel.collector.metrics.port=4318
quarkus.otel.exporter.otlp.traces.endpoint=http://${mf.otel.collector.host}:${mf.otel.collector.traces.port}
quarkus.otel.resource.attributes=${mf.resource.attributes}
quarkus.micrometer.export.otlp.enabled=false
quarkus.micrometer.export.otlp.url=http://${mf.otel.collector.host}:${mf.otel.collector.metrics.port}/v1/metrics
quarkus.micrometer.export.otlp.resourceAttributes=${mf.resource.attributes}
#keep true for native build as this build time property, see DatadogBuildConfig
quarkus.micrometer.export.datadog.enabled=true
quarkus.micrometer.export.datadog.apiKey=${MF_DATADOG_API_KEY:undefined}


quarkus.config.locations=geo-access-list.yaml
mf.geo.redirect.uri = /static/forbidden.html

mf.platforms.megafair.baseURL=https://prod.bsg-mock.mfgapi.com
mf.platforms.megafair.redirectURL=https://prod.bsg-mock.mfgapi.com/homeUrl

mf.security.private-key."mf-jwt".path = jwt_keys/mf/privateKey-mf-jwt.pem
mf.security.private-key."mf-jwt".secret = 770A8A65DA156D24EE2A093277530142
mf.security.public-key."mf-jwt".path=jwt_keys/mf/publicKey-mf-jwt.pem

quarkus.security.security-providers=BC
mf.traffic.encryption.keys.1=147b75930f3a437b9d50ea4aea816c14
mf.traffic.encryption.keys.2=12efeead3b9d4e8681c4c4cbb2704fca
mf.traffic.encryption.keys.3=d7f32c1d767c4729936f4d1a24bb3002
# Scheduler config
quarkus.scheduler.metrics.enabled=true
quarkus.scheduler.tracing.enabled=true
quarkus.scheduler.start-mode=forced

# Association cache config
mf.conf.cached-service.assc.generation=20250526_1
mf.conf.cached-service.assc.cron.expr=0/5 * * * * ?

# feature toggle cache config
mf.conf.cached-service.features.generation=20250526_1
mf.conf.cached-service.features.cron.expr=0/5 * * * * ?

# PLAYER_SEGMENTATION_CACHE_KEY cache config
#mf.conf.cached-service."PLAYER_SEGMENTATION_CACHE_KEY".generation=20240906_1
#mf.conf.cached-service."PLAYER_SEGMENTATION_CACHE_KEY".cron.expr=0/5 * * * * ?

# Tournament cache config
mf.conf.cached-service.tournamentsConfig.generation=20250526_1
mf.conf.cached-service.tournamentsConfig.cron.expr=0/5 * * * * ?

# Currency cache config
mf.conf.cached-service.currency.generation=20250526_1
mf.conf.cached-service.currency.cron.expr=0/5 * * * * ?
#mf-fnd-currency-exchange.scheduler.enabled=true
#mf-fnd-currency-exchange.scheduler.cron=0 0 * * * ?

#setting service cache config
mf.conf.cached-service.settings.generation=20250526_1
mf.conf.cached-service.settings.cron.expr=0/5 * * * * ?
mf.conf.cached-service.settings.cron.enabled=true

quarkus.log.category."io.megafair.jinfra.foundation.utils.loader.AroundInvokerFactory".level=DEBUG
quarkus.log.category."io.megafair.jinfra.foundation.utils.cache.producer.AbstractCachedServiceCommon".level=DEBUG
quarkus.log.category."io.megafair.jinfra.foundation.cache.core.consumer.CachedServiceContextProvider".level=DEBUG

mf.security.pl-master-key."test-key".secret=test-key
mf.security.pl-master-key."240703-01-mfmp".secret=${MF_MASTER_PASSWORD_PASS1:}


quarkus.log.console.json.additional-field."instanceId".value: ${quarkus.uuid}
quarkus.log.console.json.additional-field."instanceId".type: string
quarkus.log.console.json.additional-field."commit.hash".value: ${git.commit.id.abbrev}
quarkus.log.console.json.additional-field."commit.hash".type: string

#analytics module configuration
mf-fnd-analytics.settings.real=${MF_ANALYTICS_SETTINGS_REAL:undefined}
mf-fnd-analytics.settings.demo=${MF_ANALYTICS_SETTINGS_DEMO:undefined}

mf.conf.supported-protocol=vibra

mf.conf.contract.s2s.jwt.secret-key=mf-jwt
#mf.conf.contract.s2s.front-api.url=https://vibra-api.local.mfgapi.com/initData
mf.conf.contract.s2s.front-api.url=https://mf-dev-int.apistg.com/vibra-api/initData

mf.registration.transaction.mode=http
