name: Manually deploy Docker image
run-name: >
  ${{ github.event_name == 'pull_request' && format('PR: {0}', github.event.pull_request.title) 
  || github.event_name == 'push' && format('Commit: {0}', github.event.head_commit.message) 
  || format('Deploy to {0}', github.event.inputs.envToDeploy) }}
on:
  workflow_dispatch:
    inputs:
      envToDeploy:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - d00
          - d01
          - d02
          - d03
          - d04
          - d05
          - dev
          - dev-int
          - load-1
          - load-2
          - load-3
          - load-4
          - load-5
          - main
      imageTag:
        description: 'Docker image tag'
        required: true
        type: string
        default: 'latest'

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    uses: MegaFair/mf-ci-center/.github/workflows/deploy-backend.yml@v1.135.0
    with:
      runner_label: "mf-dev-github-runner"
      app_name: "vibra-s2s-api"
      env_to_deploy: "${{ github.event.inputs.envToDeploy }}"
      docker_tag: "${{ github.event.inputs.imageTag }}"
    secrets:
      aws_source_account: "${{ secrets.AWS_SOURCE_ACCOUNT }}"
      jira_github_token: "${{ secrets.MF_GIT_TOKEN }}"
      github_pat: "${{ secrets.MF_GIT_TOKEN }}"

  notify:
    if: always()
    needs:
      - deploy
    uses: MegaFair/mf-ci-center/.github/workflows/notify-slack.yml@v1.135.0
    with:
      build_status: "skipped"
      deploy_status: ${{ needs.deploy.result }}
      environment: "${{ github.event.inputs.envToDeploy }}"
      docker_tag: "${{ github.event.inputs.imageTag }}"
      send_slack_notification: "true"
    secrets:
      slack_webhook_url: "${{ github.event.inputs.envToDeploy == 'main' && secrets.MF_MAIN_DEPLOY || github.event.inputs.envToDeploy == 'prod-int' && secrets.MF_PROD_INT_DEPLOY || (github.event.inputs.envToDeploy == 'd00' || github.event.inputs.envToDeploy == 'd01' || github.event.inputs.envToDeploy == 'd02' || github.event.inputs.envToDeploy == 'd03' || github.event.inputs.envToDeploy == 'd04' || github.event.inputs.envToDeploy == 'd05') && secrets.MF_DOX_DEPLOY || '' }}"
